baseurl = "https://example.org/"
languageCode = "en-us"
title = "Eastinco page"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "John Doe"
    site_description = "The awesome blog of John Doe."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Eastinco Consulting"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "yuqianguk"
    gplus     = ""
